{{- range $cmName, $cmData := $.Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
data:
{{- range $cmDataKey, $cmDataValue := $cmData }}
{{- if kindIs "map" $cmDataValue }}
  {{ $cmDataKey }}: |
  {{- toYaml $cmDataValue | nindent 4 }}
{{- else }}
  {{ $cmDataKey }}: |
    {{- $cmDataValue | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
