{{- $cmDataTypeMap := dict "yaml" "yaml" "yml" "yaml" "ini" "ini" "properties" "properties" }}
{{- range $cmName, $cmData := $.Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
data:
{{- range $cmDataKey, $cmDataValue := $cmData }}
  {{ $cmDataKey }}: |
  {{- if or (hasSuffix ".yaml" $cmDataKey) (hasSuffix ".yml" $cmDataKey) }}
  {{- toYaml $cmDataValue | nindent 4 }}
  {{- else if hasSuffix ".properties" $cmDataKey }}
  {{- range $propertyName, $propertyValue := $cmDataValue }}
    {{ printf "%s = %s" $propertyName $propertyValue }}
  {{- end }}
  {{- else if hasSuffix ".ini" $cmDataKey }}
  {{- range $sectionName, $sectionData := $cmDataValue }}
    {{ printf "[%s]" $sectionName}}
  {{- range $propertyName, $propertyValue := $sectionData}}
    {{ printf "%s = %s" $propertyName $propertyValue}}
  {{- end }}
  {{- end }}
  {{- else if hasSuffix ".json" $cmDataKey }}
    {{ toJson $cmDataValue }}
  {{- else }}
  {{ $cmDataValue | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
