{{- range $jobName, $jobConf := $.Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
    {{- include "get.labels" $jobConf | nindent 4 }}
  annotations:
    {{- include "config.checksum" $.Values | nindent 4 -}}
    {{- include "get.annotations" $jobConf | nindent 4 }}
spec:
  {{- with $jobConf.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  template:
    spec:
      {{- include "spec.pod" $jobConf.pod | nindent 6 }}
{{- end }}
