{{- range $secretName, $secretConf := $.Values.sealedSecrets }}
---
apiVersion: {{ default "bitnami.com/v1alpha1" $secretConf.apiVersion }}
kind: SealedSecret
metadata:
  name: {{ $secretName }}
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
spec:
  encryptedData:
    {{- toYaml $secretConf.encryptedData | nindent 4 }}
  {{- with $secretConf.template }}
  template:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
