{{- range $secretName, $secretData := $.Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
{{- range $keyName, $keyValue := $secretData }}
  {{ $keyName }}: "{{ $keyValue | b64enc }}"
{{- end }}
{{- end }}
