{{- range $secretName, $secretData := $.Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
data:
{{- range $secretDataKey, $secretDataValue := $secretData }}
{{- if kindIs "map" $secretDataValue }}
  {{ $secretDataKey }}: |
    {{- toYaml $secretDataValue | b64enc | nindent 4}}
{{- else }}
  {{ $secretDataKey }}: |
    {{- $secretDataValue | b64enc | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
