{{- range $saName, $saData := $.Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $saName
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
    {{- include "get.labels" $saData | nindent 4 }}
  {{- with ($saData.metadata).annotations }}
  annotations:
  {{- include "get.annotations" $saData | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $saData.automountServiceAccountToken | default true }}
{{- with $saData.imagePullSecrets }}
imagePullSecrets:
  {{ toYaml . | nindent 2 }}
{{- end }}
{{- with $saData.secrets }}
secrets:
  {{ toYaml . | nindent 2}}
{{- end }}
{{- end }}
