#values.yml
customResources:
  kafkaTopic1:
    definition:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      metadata:
        labels:
          strimzi.io/cluster: some-cluster
      spec:
        partitions: 3
        replicas: 3
    instances:
      some-topic:
        spec:
          config:
            retention.ms: 96000
      another:
        metadata:
          labels:
            extraLabel: someLabelValue
